#
# DO NOT EDIT THIS FILE!!!
#
# Edit .\dirs if you want to add a new directory to this component. This
# file merely indirects to the real make file that is shared by all components
# of the operating system.
#
include $(TOOLSDIR)/default-dirs.mk
